name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi=0.104.1
  - uvicorn=0.24.0
  - pydantic=2.5.0
  - python-dotenv=1.0.0
  # uvicorn[standard] dependencies
  - uvloop
  - httptools
  - websockets
  - watchfiles
